### ISSUE TITLE
Missing dependency 'object scala in compiler mirror'

### ISSUE THREAD

**Issue by apradhan** [AtomicScala/atomic-scala-corrections#35]
From Activator >> Run >> ExampleRunner  with Try.scala  gives the following error. If there is a solution somewhere, please provide link. thanks.

error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by C:\Program Files\Java\jdk1.8.0_05\jre\lib\rt.jar(java/lang/Object.class)
Exception in thread "main" scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
    at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
    at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
    at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:173)
    at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage$lzycompute(Definitions.scala:161)
    at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage(Definitions.scala:161)
    at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass$lzycompute(Definitions.scala:162)
    at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass(Definitions.scala:162)
    at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1392)
    at scala.tools.nsc.Global$Run.<init>(Global.scala:1216)
    at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$compile$1(ScriptRunner.scala:110)
    at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:161)
    at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
    at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
    at scala.tools.nsc.util.package$.trackingThreads(package.scala:43)
    at scala.tools.nsc.util.package$.waitingForThreads(package.scala:27)
    at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:128)
    at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:192)
    at utils.RunFile$.apply(RunFile.scala:12)
    at ExampleRunner$.delayedEndpoint$ExampleRunner$1(ExampleRunner.scala:3)
    at ExampleRunner$delayedInit$body.apply(ExampleRunner.scala:1)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at ExampleRunner$.main(ExampleRunner.scala:1)
    at ExampleRunner.main(ExampleRunner.scala)

**Comment by dave-gil** [comment]
Exact same problem for me

**Comment by jamesward** [comment]
I've just pushed a change that should fix this:
https://github.com/AtomicScala/atomic-scala-examples/pull/7/files

You can either manually apply the change or re-download the project.

Feel free to reopen this if it still doesn't work.

**Comment by dave-gil** [comment]
works perfectly now, thanks!
